### ISSUE TITLE
Security issue (Passwort)

### ISSUE THREAD

**Issue by mkretzschmar** [demel42/IPSymconAutomowerConnect#2]
Hallo demel42,

mir ist aufgefallen, dass an mehreren Stellen das Passwort im Klartext angezeigt wird.
- Im Konfigurator --> besser Passwort-Feld statt Text-Feld
- Im Debug-Log (hier bitte entweder ganz entfernen/filtern oder wenigstens nur als Hash anzeigen)

Vielen Dank :-)

**Comment by demel42** [comment]
In der IO-Instanz: erledigt
Im Debug geht das nicht wirklich gut, da müsste ich bei jedem Modul und jeder Ausgabe das manuell angepasst herausholen. Und manchmal braucht man das bei der Entwicklung ja auch
