### ISSUE TITLE
API Login change

### ISSUE THREAD

**Issue by MasterMNB** [demel42/IPSymconAutomowerConnect#5]
The login was again changed to get the token there is now instead of the username and password a "Application secret" (client_secret).

Example to curl the token of the documentation:
`curl -X POST -d "grant_type=client_credentials&client_id=********-****-****-****-************&client_secret=********-****-****-****-************" https://api.authentication.husqvarnagroup.dev/v1/oauth2/token`

Older API connections are still working, but new created are not and it is only a matter of time until existing API connections are not longer working.

**Comment by demel42** [comment]
Change is comittet as version 2.7
